### ISSUE TITLE
Create "How to use eslint" for a MagicMirror module (with v8 and v9)

### ISSUE THREAD

**Issue by KristjanESPERANTO** [MagicMirrorOrg/MagicMirror-3rd-Party-Modules#11]
We recommend using ESLint in [the issue list](https://github.com/KristjanESPERANTO/MagicMirror-3rd-Party-Modules/blob/main/result.md). It would be good if we could write a guide on how to do this in best practice.

As the classic configuration is still widely used, there should be instructions for the classic configuration and also for the planned future configuration ([flat config](https://eslint.org/blog/2023/10/flat-config-rollout-plans/)).

I'll try to do this myself soon. Support and feedback is of course also welcome :slightly_smiling_face:

**Comment by dathbe** [comment]
After I saw what you did on one of my modules, I think the steps are fairly easy:

# 1
Add a `.github/workflow/automated-tests.yaml` file with the following text:

```yaml
name: Automated Tests
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]

permissions:
  contents: read

jobs:
  run-lint:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Check linting
        run: npm run lint
      - run: echo "🍏 This job's status is ${{ job.status }}."
```

# 2
Add a `eslint.config.mjs` file to the top directory with the following text:

```js
import eslintPluginJs from '@eslint/js'
import eslintPluginStylistic from '@stylistic/eslint-plugin'
import globals from 'globals'

const config = [
  eslintPluginJs.configs.recommended,
  eslintPluginStylistic.configs.recommended,
  {
    files: ['**/*.js'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        Log: 'readonly',
        Module: 'readonly',
        config: 'readonly',
      },
      sourceType: 'commonjs',
    },
    rules: {
    },
  },
  {
    files: ['**/*.mjs'],
    languageOptions: {
      ecmaVersion: 'latest',
      globals: {
        ...globals.node,
      },
      sourceType: 'module',
    },
    rules: {
    },
  },
]

export default config
```

# 3
Add the following to the bottom of your `package.json` file:

```js
"devDependencies": {
    "@eslint/js": "^9.23.0",
    "@stylistic/eslint-plugin": "^4.2.0",
    "eslint": "^9.23.0",
    "globals": "^16.0.0"
  }
``` 

# 4 (optional)
Add explanation to `README`:

```
### Developer commands

- `npm run lint` - Run linting checks.
- `npm run lint:fix` - Fix automatically fixable linting errors.
```
